In [1]:
import numpy as np
import torch
from torch import Tensor

from train import ModelManager
from utils import get_loader, get_cifar100

# globals
NUM_CLASSES = 100
BATCH_SIZE = 25
NUM_TRAIN = 50000
NUM_TEST = 10000
EPOCHS = 100

NOTEBOOK_NAME = 'resnet18_cifar100'
print('train on:', ModelManager.DEVICE)

train_idx = np.arange(NUM_TRAIN, dtype=int)
test_idx = np.arange(NUM_TEST, dtype=int)
dataset_train, dataset_test, dataset_train_for_test, dataset_train_raw = get_cifar100()
loader_train = get_loader(dataset_train, train_idx, BATCH_SIZE, shuffle=True)
loader_test = get_loader(dataset_test, test_idx, BATCH_SIZE, shuffle=False)
loader_train_ordered = get_loader(dataset_train_for_test, train_idx, BATCH_SIZE, shuffle=False)
Y_train = Tensor(dataset_train.targets)[train_idx].type(torch.int64)
Y_test = Tensor(dataset_test.targets)[test_idx].type(torch.int64)

train on: cuda
Files already downloaded and verified
Files already downloaded and verified


In [2]:
#  self.optimizer: torch.optim.Adam = optim.Adam(self.model.parameters(), lr=1e-3, weight_decay=.5e-4)  # lr=1e-4
#  self.scheduler: torch.optim.lr_scheduler.MultiStepLR = \
#  optim.lr_scheduler.MultiStepLR(self.optimizer, milestones=[50, 65, 70, 75, 80, 85, 90, 95], gamma=0.3)
#  BATCH_SIZE = 25
#  t=
model1 = ModelManager(num_classes=NUM_CLASSES, model_name='model1', dir_=NOTEBOOK_NAME, load=False)
model1.train(loader_train, loader_test, loader_test, EPOCHS)

Epoch 0 Train:                                                               0/2000 [00:00<?, ? batch/s]

KeyboardInterrupt: 

In [20]:
# i = iter(loader_train_ordered)
# print(next(i))


[[255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 252 248]
 [231 222 213]
 [176 168 163]
 [237 236 235]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [252 255 255]
 [242 252 252]
 [229 240 234]
 [195 205 193]
 [212 224 204]
 [182 194 167]]
